name: blocked
description: A creative spin on the classic sliding puzzle game.

publish_to: "none"

version: 10.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.7.2
  async: ^2.13.1
  audio_session: ^0.2.2
  google_mobile_ads: ^8.0.0
  firebase_core: ^3.15.2
  firebase_remote_config: ^5.5.0
  equatable: ^2.0.8
  flex_color_scheme: ^8.4.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.0.1
  google_fonts: ^8.1.0
  yaml: ^3.1.0
  just_audio: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

dependency_overrides:
  path_provider_android: ^2.3.1
  path_provider: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/bgm_forest.wav
    - assets/audio/sfx_hit.wav
    - assets/audio/sfx_slide.wav
    - assets/audio/sfx_tap.wav
    - assets/audio/sfx_win.wav
    - assets/ui/
    - assets/ui/home/
    - assets/ui/map/
    - assets/ui/play/
    - assets/ui/complete/
    - google_fonts/
